### ISSUE TITLE
Intermittent communications failures, particularly over LoRa

### ISSUE THREAD

**Issue by acehoss** [acehoss/rnsh#16]
I've seen some intermittent but repeatable failures while testing on LoRa links. Even at higher bandwidths, sessions will spontaneously stop communicating. The exact circumstances are still unclear, but I have a few data points.

- 911.325 MHz, BW 500 KHz, SF 8, CR 5
- Connect an `rnsh` session
- Run `top -s 30` (macOS) or`top -d 30` for Linux -- to keep data running over the session
- After some amount of time on the order of 5 minutes, no more refreshes will be sent
- The listener may show that the process has been terminated and the link has been closed.
- The initiator will likely show nothing, even with a couple of `-v`s
- Typing on the initiator session will cause a packet to be sent. This will eventually retry out.
- **Big frustration** At this point, initiating a new session may fail to connect link, or actually start the session and remote process but send no data.
- Since the listener sends no data, the initiator tty is not yet in raw mode and a Ctrl-C will terminate the session.
- Restarting the listener restores ability to connect.

The issue could be at any layer: `rnsh`, Reticulum, or RNode. Often it looks like packets aren't being received on one end or the other.

**Comment by acehoss** [comment]
This is probably fixed by https://github.com/markqvist/Reticulum/commit/f522cb1db184474ebfc34676cf01e815ea247193#r112605249

**Comment by markqvist** [comment]
Yes, I suspect it will be as well. I am testing all the latest changes over low-bandwidth LoRa now, and will let you know how it goes.

**Comment by markqvist** [comment]
I currently have three separate `rnsh` sessions going, initiated from the same system, and running via a shared `rnsd` instance.

- One is a fast link connecting to a local system only one hop away. Session is showing `bpytop` output with a refresh interval of 700ms.
- Another is medium speed link connecting over a mix of interfaces to a system 4 hops away, showing `htop` output at 1 second refreshes.
- The last one is connecting over 3 hops, the last one being a slow LoRa link of 1.3 Kbps, showing `top` output refreshing every 90 seconds.

All are running perfect, and going on 30 minutes now :) The `Channel` compression has helped a bit with responsiveness and usability over slow LoRa links too.

**Comment by acehoss** [comment]
Amazing! I was really sweating this, and it showed up just as I ran out of time to really dig into it. Looking forward to the next release so I can get this rolled in!

**Comment by markqvist** [comment]
I added some **very** basic windowing to `Channel` as well by the way. It's rudimentary, but at least the framework for improving it in the future is there, and it alleviates having to wait for a proof for each packet on faster links for now.

I'll do a bit more testing, but probably release it soon if everything works out OK :)

**Comment by markqvist** [comment]
Allright, I released RNS `0.5.2`, with the mentioned changes. Pretty sure it fixes this issue, as I have not been able to replicate anything like it anymore, neither on fast nor slow links.

At your leisure, it'd be awesome with an updated release of `rnsh` that targets `rns >= 0.5.2` :)

**Comment by acehoss** [comment]
On it!

**Comment by acehoss** [comment]
Sigh. Well, it happened again. Interestingly, it happened at the same time from one client machine to two different servers. 

*Events*
1. Session 1 running `top` over `rnsh` over LoRa to a BananaPi.
2. Session 2 running a shell session over `rnsh` over ethernet to a Mac.
3. In session 2, I ran the shell equivalent of `10 PRINT HELLO; 20 GOTO 10`. Control-C would not terminate it.
4. I closed the terminal. I'm not sure if the Python process was killed.
5. I switched to the session 1 terminal. The session was not open any longer.
6. I tried reconnecting session 1. I saw the receive indication on the RNode connected to the BananaPi, but it didn't respond.
7. I restarted the `rnsh` service on the BananaPi and tried connecting again. It connected.
8. I tried reconnecting session 2, it timed out.
9. I started writing up this issue. Probably 5 minutes passed.
10. I tried reconnecting session 2 without restarting the `rnsh` listener. This time it connected.

I still need to collect more data on this. The fact that instability of one session crashed the other makes me think that this has something to do with the shared RNS instance. It might actually have nothing to do with the remote listener.

An interesting experiment:

1. Open two sessions from one machine to two others
2. Crash one of them. Confirm that the other is broken and/or that no additional sessions can be opened
3. Try connecting to either/both of the other machines from another machine (or a different RNS instance)

If step 3 works, then this is probably an issue with the shared RNS instance or the way `rnsh` is using it.

**Comment by acehoss** [comment]
This appears to be related to buffered data. 

1. I started a transfer of a few megs of interactive data from a shell script
2. it was enough data that the data was still only 1/4 received by the client a full minute or two after the generator command was finished
3. killed the session from the client side before the transfer was complete (closed terminal tab)
4. immediately tried connecting again
5. the connect was successful, but the server didn't send the shell prompt
6. killed *that* session
7. tried connecting again, successful this time

**Comment by markqvist** [comment]
Hmm, there's something interesting going on here. I am not currently sure whether it is local to `rnsh`, the RNS `Buffer` implementation, or the internal Python `BufferedIOBase` handling being in some sort of mismatch with our implementations. When I have some time for it, I'll try and experiment with it, and report back if I find anything useful.

**Comment by acehoss** [comment]
Fixed by [Improved pipe management](https://github.com/acehoss/rnsh/commit/ab7f43e9106ff74303a9add671203e8899f0e1ef)

**Comment by acehoss** [comment]
Well, actually this wasn't fixed by *this* one, probably by one of @markqvist's RNS fixes.
