### ISSUE TITLE
Dependency compatibility for rns 0.5.1

### ISSUE THREAD

**Issue by markqvist** [acehoss/rnsh#17]
Hi @acehoss!

I was wondering if you could update the rns dependency for `rnsh` to `rns >= 0.5.0` instead of `rns == 0.5.0`, as it is now. I just released RNS `0.5.1`, and due to the dependency issue, `rnsh` is giving dependency errors in `pip`.

Also, when you have time, I sent you a message on matrix :)

**Comment by acehoss** [comment]
Yeah, I remember noticing that right after pushing out v0.0.13 but thinking I'd fix it in the next version…but then another version wasn't really needed. Fix will be up shortly.
