### ISSUE TITLE
Lack of non-tty mode breaks some scripts

### ISSUE THREAD

**Issue by acehoss** [acehoss/rnsh#3]
Without a non-tty mode, the remote command's `stderr` is redirected to `stdout`, and this causes issues--particularly with binary streams. This is why the file transfer with tar over a pipe doesn't work--there is some stray information printed to `stderr` at the beginning of the transfer that mangles the tar stream. A forced non-tty mode is needed, like `ssh -T` that causes `stderr` to be sent as a separate stream.

On the remote end, this would be implemented by opening three pipes with `os.pipe(…)`, calling `os.fork()`, and then connecting the pipes to the correct file descriptors with `os.dup2(...)`. 

The current implementation using `pty.fork()` still needs to be used for tty mode, otherwise the remote command doesn't think it is connected to a tty and won't provide interactive features.

**Comment by acehoss** [comment]
On the initiator side, `os.isatty(fd)` will be `False` when the `fd` is connected to a pipe. This means that all three of `stdin`, `stdout`, and `stderr` can and should be checked for `os.isatty()` and that information should be sent to the listener on connect. When the listener goes to fork, it should connect use pipes instead of the pty as appropriate.

**Comment by acehoss** [comment]
[ChatGPT wrote the solution](https://chat.openai.com/chat/97b2a169-8a13-4b3e-8fba-c3e2d8392844). Incidentally, this removes the need for `psutil` as well so assuming it works, it would solve #5 as well.

**Comment by acehoss** [comment]
I was able to run tar over the remote to local pipe now to transfer files. A message was printed to the local stderr and the file arrived intact. 

`rnsh a5f72aefc2cb3cdba648f73f77c4e887 -- tar czf - /tmp/test.txt | tar xvzf - -C .`

Some anecdotal testing did not encounter issues, and the automated test suite (only interactive tests currently) passed. Automated tests should be written to exercise a few combinations of pipes/pty. Those tests will pay off later when working on protocol or threading stuff.

**Comment by markqvist** [comment]
This is quite a milestone!
