### ISSUE TITLE
Rework protocol handling for better version compatibility

### ISSUE THREAD

**Issue by acehoss** [acehoss/rnsh#4]
Refactor the protocol handling parts of the application to use an interface that can be implemented by multiple protocol versions. This way, when new features are added to the protocol, older versions can interoperate for a longer time.

**Comment by markqvist** [comment]
I think this is a good idea, but  it's also probably not something to worry too much about until at least a `v0.1.0` release or something.

Personally at least, I am in favor of just throwing out all the old protocol compatibility until a certain level of functionality/stability is reached, in the service of not clogging up the codebase with case handling for all kinds of stuff that will get buried in deprecation quickly anyway.

When that cut-off point is, though, is not something I have anything intelligent to say about ;)

**Comment by acehoss** [comment]
I'm with you! And I've had a couple rounds of breaking the protocol already. The protocol now at least includes version compatibility checking. And in some brief attempts at managing reverse compatibility, it was clear that the way I'm doing things will not scale.

The v0.1.0 beta release is a good target for this, I think. I want to also make a shift to using only the `Packet` API, and that might be a good point to define that interface.
