### ISSUE TITLE
Linux will show docopts but silently exits when real options specified

### ISSUE THREAD

**Issue by acehoss** [acehoss/rnsh#7]
After installing the dev build from wheel, `rnsh` just returns to the command line if a valid set of options is specified, even just `-p`. Adding verbose flags doesn't change anything.

```
OS: Ubuntu 20.04.4 LTS x86_64 
Host: SEi TBD by 
Kernel: 5.15.0-58-generic 
Uptime: 28 days, 19 hours, 8 mins 
Packages: 2066 (dpkg), 9 (snap) 
Shell: bash 5.0.17 
Resolution: 1280x720 
Terminal: /dev/pts/3 
CPU: Intel i5-8279U (8) @ 4.100GHz 
GPU: Intel Iris Plus Graphics 655 
Memory: 7803MiB / 15841MiB 
```

**Comment by markqvist** [comment]
I'm not sure this is a universal thing. With `rnsh` installed from 64fec6e012f3e840d1199a6dc274b695580d41f9, everything seems to be working very well on (Manjaro) Linux. Both listener and initiator modes functions as expected.

And just so you know, the hang on exit does not occur any more either, your previous commits fixed that :)

**Comment by acehoss** [comment]
And it works fine in a venv on that machine. I'm going to say it's something to do with with conflicts between the system version and the additional versions I installed.
